version: '2'
services:
  jam-wui:
    image: avvero/jam-wui:latest
    container_name: jam-wui
    environment:
      - app.jira.host=http://localhost:8081
      - app.jira.username=admin
      - app.jira.password=admin
    ports:
      - "8080:8080"
